export {default as Header} from "./Header"
export {default as Home} from "./Home"
export {default as Footer} from "./Footer"
export {default as Videos} from "./Videos"
export {default as Upload} from "./Upload"
export {default as Login} from "./Login"
export {default as SignUp} from "./SignUp"